triggers:
  - type: meya.wit
    properties:
        token: 7U2TR6KQE53IV5EGHIDJVE4K5ABINBKV
route: true
states:
  greeting:
    flow: greeting
    return: true
  upgrade:
    flow: upgrade
    return: true
  cancel:
    flow: cancel
    return: true
