triggers:
  - type: meya.keyword
    properties:
        keyword: upgrade_promo
states:
    unlock:
        component: meya.text
        properties:
            text: Ooh, looks like you have unlocked the "{{ user.referral }}" special!
    upgrade:
        flow: upgrade